### ISSUE TITLE
Make it possible to have sections of marathon/chronos/adhoc yaml files that aren't treated as instances

### ISSUE THREAD

**Issue by EvanKrall** [Yelp/paasta#1226]
YAML has the neat anchor/alias features, which allows for composition of dictionaries together.

However, every top-level entry in a marathon/chronos/adhoc.yaml is treated as a service instance, which means that there's no way to create an instance "template" that isn't used directly -- we can only reuse configs of other instances.

This can sometimes lead to surprising results. As an example, the following is a pretty standard use of anchors to reduce config duplication:

```yaml
main: &main_template
  cpus: 2
  mem: 5000
  instances: 30
  deploy_group: prod.main
  registrations: ['my-cool-service.main']
  env:
    ...

canary:
  <<: *main_template
  instances: 2
  deploy_group: prod.canary
```

If we now want to autoscale the main instance, we'd replace `instances` with `min_instances` and `max_instances` and maybe some `autoscaling` params:

```yaml
main: &main_template
  cpus: 2
  mem: 5000
  min_instances: 5
  max_instances: 40
  deploy_group: prod.main
  env:
    ...

canary:
  <<: *main_template
  instances: 2
  deploy_group: prod.canary
```

Except, oops! We just enabled autoscaling on canary, because canary does not override min_instances/max_instances.

We could flip it around, so that canary becomes the template, and main inherits from it, and that would solve this particular problem. However, we have some services that use `bounce_method: brutal` on canary to speed up deployments. Brutal is fine for canary, which represents a small fraction of capacity, but it would not be okay for main. We could solve this by overriding `bounce_method` on main, but we'd have to remember to override this for every instance that inherits from the same reference.

# Proposal 1:

We could have a dedicated top-level key which we totally ignore, under which you could construct whatever templates you like:

```yaml
__templates__:
  main_template: &main_template
    cpus: 2
    mem: 5000
    registrations: ['my-cool-service.main']
    env:
      ...

main:
  <<: *main_template
  instances: 30
  deploy_group: prod.main

canary:
  <<: *main_template
  instances: 2
  deploy_group: prod.canary
```

# Proposal 2:

We could ignore any top-level key that matches some pattern, like if it starts with an underscore:

```yaml
_main_template: &main_template
  cpus: 2
  mem: 5000
  registrations: ['my-cool-service.main']
  env:
    ...

main:
  <<: *main_template
  instances: 30
  deploy_group: prod.main

canary:
  <<: *main_template
  instances: 2
  deploy_group: prod.canary
```
