### ISSUE TITLE
Apply a default constraint that prevents all instances from being deployed to one box

### ISSUE THREAD

**Issue by EvanKrall** [Yelp/paasta#335]
In the mean time, for small services (where # instances <<  # hosts), we should apply a `["hostname", "UNIQUE"]` constraint. For larger services we should consider `['hostname', "GROUP_BY", 5]` or something, which would prevent more than ~20% of instances from ending up on one box (albeit with the issues listed in mesosphere/marathon#3515).

If https://github.com/mesosphere/marathon/issues/3515 gets implemented, we should switch to that, based on a percentage of the instances or something.

**Comment by Rob-Johnson** [comment]
I had a think about this today and I'd like to get started  - here are some thoughts/questions:

- We'd have to take other constraints into account when calculating the number of slaves available -  attributes are made available in mesos' ``state.json``, but it's worth remembering.
- Currently we **don't** bounce when the instance count in soa-configs changes, but this wouldn't be the case if the instance count crossed the threshold from < number of slaves to >= number of slaves. Is this OK?
- If we add the ``['hostname', "GROUP_BY", n]`` constraint, where n is ``instances``/``slaves`` then we'd bounce every time we lost a slave. This is probably too much churn, and we need to come up with a way for it to be less sensitive.

**Comment by mittonk** [comment]
I had 40% of my instances end up on one box, which then slowed down.  There's 10+ available hosts, better distribution would be helpful here.

**Comment by solarkennedy** [comment]
I don't like the idea of applying this constraint automatically, what if we added it to the defaults in the fsm template? (assuming I ship my comment'd fsm template idea) Like this:

```
# marathon-PROD.yaml
main:
  # This is a starting instance count, as your service gets more traffic, please
  # check out $autoscaling docs to see how to scale the instances with load
  instances: 3
  # This extra constraint ensures the service instances don't all get scheduled to the
  # the same box. It is in general a good idea, but needs to be removed the service
  # has more than say, 3 instances. For example if the service is scaled up to 100
  # instance and we don't have 100 unique hostnames, it won't work.
  extra_constraints: ["hostname", "UNIQUE"]
```
