### ISSUE TITLE
Create HTTP drain method

### ISSUE THREAD

**Issue by EvanKrall** [Yelp/paasta#514]
It would be good to have a drain method that can make fairly arbitrary HTTP calls for its implementation of `drain`, `undrain`, `is_draining`, `safe_to_kill`.

I'm thinking something whose config could look like this:

```
main:
  cpu: 1
  mem: 100
  drain_method: http
  drain_method_params:
    drain:
      url_format: http://{host}:{port}/drain
      method: PUT
    undrain:
      url_format: http://{host}:{port}/drain
      method: DELETE
    is_draining:
      url_format: http://{host}:{port}/drain
      method: GET
      success_codes: 200-399
    is_safe_to_drain:
      url_format: http://{host}:{port}/drain
      method: GET
      success_codes: 200
```

I'm imagining we'd make several things available in `url_format`, maybe:

 - `{host}`: the ip or hostname of the slave this task is running on
 - `{port}`: the allocated port for this container
 - `{service_name}`: the name of the service
 - `{instance_name}`: the name of the instance
 - `{nerve_ns}`: the nerve namespace of this instance
 - `{git_sha}`: the 7-hex-digit git SHA prefix that we put into the task ID
 - `{config_hash}`: the 7-hex-digit config hash in the task ID
