### ISSUE TITLE
local-run has some issues with cmd quoting

### ISSUE THREAD

**Issue by keshavdv** [Yelp/paasta#555]
The following job config doesn't work as expected as the command is incorrectly quoted when passed to `sh -c`:

```
example_chronos_job:
  cmd: "echo 'Hello' && sleep 60"
  schedule: 'R/2016-04-15T06:00:00Z/PT24H'
  schedule_time_zone: 'America/Los_Angeles'
```

This turns into:
`sh -c 'echo foo '"'"'&&'"'"' sleep 60'`
